# A Proto TOML plugin for x.com's xurl cli:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "xurl"
type = "cli"

[platform.linux]
download-file = "xurl_Linux_{arch}.tar.gz"

[platform.macos]
download-file = "xurl_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "xurl_Windows_{arch}.zip"

[install]
download-url = "https://github.com/xdevplatform/xurl/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"

[resolve]
git-url = "https://github.com/xdevplatform/xurl"
